### PR TITLE
Edit the displayed hex codes to match the actual colors

### PR DESCRIPTION
**Pull request by mizejewski**

### CODE REVIEW

**Comment by mizejewski** [comment]
Looks like the change is not live yet, because something travis-related failed?

**Comment by Okami-** [comment]
It's live in the code base, you can see your diff at https://github.com/ucsf-web-services/shoestring/commit/85cce16c4563e1d62982c918f8072f9a1870ddb8 . 

The github pages website is manually released with releases per release number.

**Comment by mizejewski** [comment]
Thanks for clarifying :)

**Comment by Okami-** [comment]
Thanks for contributing :+1:  !

**Pull request merged**
