### PR TITLE
added svg logo and styles

### PR DESCRIPTION
**Pull request by Okami-**

### CODE REVIEW

**Comment by stopfstedt** [comment]
the logo looks jacked in FF 35.0.1/Linux

selection_015

**Comment by stopfstedt** [comment]
looks fine in latest Chrome/Linux, confirmed that SVG logo is applied.

**Comment by Okami-** [comment]
added background positon. Please review.

**Comment by stopfstedt** [comment]
better, but the vertical alignment of logo is off in FF. Chrome is still fine.
selection_016

**Comment by Okami-** [comment]
Oops... k .... got it now.

**Comment by stopfstedt** [comment]
Ok, looks good now. tested with IE9, IE1,1 and the latest FF and Chrome in Linux.

**Pull request merged**
