### PR TITLE
Don't merge this yet...

### PR DESCRIPTION
**Pull request by Quevin**
Richard mentioned I could use https://terabytenz.github.io/inuit.css-kitchensink/#arrows for the arrows, and really the only contribution of value here so far was to alter:
- src/assets/sass/tapestry/components/_components.scss
- src/assets/sass/ucsf/components/_components.scss

And respective files moved from/to locations in preparation. SCSS needs work still...

### CODE REVIEW

**Comment by Okami-** [comment]
FYI this library and the mixins are already implemented in shoestring

**Comment by Okami-** [comment]
Do I merge this yet?

**Comment by Okami-** [comment]
Looks to have some conflicts :3

**Comment by Okami-** [comment]
Created tabs and components cleanup

**Comment by Quevin** [comment]
ah-ha! Great! Yes, I left this straggling behind... Glad to see it's done. K

On Thu, Sep 24, 2015 at 4:28 PM, Richard Baker notifications@github.com
wrote:

> Created tabs and components cleanup
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ucsf-web-services/shoestring/pull/8#issuecomment-143078500
> .

## 

*Kevin Davison, Drupal Architect *Hook 42, Inc.
http://www.hook42.com
m: 1.415.279.7764
s:  kevinpdavison
t:   quevin

**Pull request closed without merging**
